#!/usr/bin/env ruby

forge "https://forgeapi.puppetlabs.com"

mod "egi-qc/umd",
  :git => "git://github.com/egi-qc/puppet-umd.git"

{% for mod, data in modules.items() %}
{% if data %}mod "{{ mod }}", {% if not data.repourl %}"{{ data.version }}"
{% else %}
  :git => "{{ data.repourl }}"{% if data.ref %},
  :ref => "{{ data.ref }}"{% endif %}{% endif %}
{% else %}
mod "{{ mod }}"
{% endif %}
{% endfor %}
